In [1]:
import pandas as pd

Import the calendar .csv file and examine the different columns.

In [2]:
calendar = pd.read_csv('./primary/calendar.csv')
calendar.head()

FileNotFoundError: [Errno 2] No such file or directory: './primary/calendar.csv'

"calendar" has a "listing_id" column, which is an id that maps to "id" in the "listings" and "listings-2" .csv files. To look at those next:

In [12]:
listings = pd.read_csv('./primary/listings.csv')
listings.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,22229408,https://www.airbnb.com/rooms/22229408,20230319041206,2023-03-19,previous scrape,"Explorer's Paradise: Near Train, Bus & Bike Share",Welcome to your perfect urban escape in the Na...,My home is located in the Edgewood neighborhoo...,https://a0.muscache.com/pictures/8e49b7bc-a851...,120875011,...,4.85,4.75,4.75,NaN,f,1,0,1,0,0.32
1,46951758,https://www.airbnb.com/rooms/46951758,20230319041206,2023-03-19,city scrape,Boutique Style Home - Rooftop w/Breathtaking V...,Explore or get settled in this artsy modern ro...,"Food & Drinks: Starbucks, Mama's Pizza, Busboy...",https://a0.muscache.com/pictures/miso/Hosting-...,55133178,...,4.82,4.51,4.80,Hosted License: 5007242201002380\nUnhosted Lic...,f,1,1,0,0,1.87
2,580379638076900630,https://www.airbnb.com/rooms/580379638076900630,20230319041206,2023-03-19,city scrape,Sojourn | Penthouse | Private Outdoor Space | ...,Boutique building in one of DC's best neighbor...,Dupont Circle stands out as a cosmopolitan jew...,https://a0.muscache.com/pictures/prohost-api/H...,39930655,...,NaN,NaN,NaN,NaN,f,173,154,13,5,NaN
3,594971943284098653,https://www.airbnb.com/rooms/594971943284098653,20230319041206,2023-03-19,city scrape,Quaint 1-bedroom apartment with outdoor Patio,Welcome to the center of DC. Half-way between ...,NaN,https://a0.muscache.com/pictures/5746a258-d2f7...,351398058,...,5.00,4.73,4.73,Hosted License: 5007242201002106\nUnhosted Lic...,t,3,2,1,0,1.20
4,54371126,https://www.airbnb.com/rooms/54371126,20230319041206,2023-03-19,city scrape,Waterfront Two Bedroom Apartment In a Brand Ne...,Located in Washington in the District of Colum...,NaN,https://a0.muscache.com/pictures/prohost-api/H...,395672427,...,5.00,5.00,5.00,Unhosted License: 5007242100000024,t,7,7,0,0,0.48

In [15]:
listings.columns.to_list()

['id',
 'listing_url',
 'scrape_id',
 'last_scraped',
 'source',
 'name',
 'description',
 'neighborhood_overview',
 'picture_url',
 'host_id',
 'host_url',
 'host_name',
 'host_since',
 'host_location',
 'host_about',
 'host_response_time',
 'host_response_rate',
 'host_acceptance_rate',
 'host_is_superhost',
 'host_thumbnail_url',
 'host_picture_url',
 'host_neighbourhood',
 'host_listings_count',
 'host_total_listings_count',
 'host_verifications',
 'host_has_profile_pic',
 'host_identity_verified',
 'neighbourhood',
 'neighbourhood_cleansed',
 'neighbourhood_group_cleansed',
 'latitude',
 'longitude',
 'property_type',
 'room_type',
 'accommodates',
 'bathrooms',
 'bathrooms_text',
 'bedrooms',
 'beds',
 'amenities',
 'price',
 'minimum_nights',
 'maximum_nights',
 'minimum_minimum_nights',
 'maximum_minimum_nights',
 'minimum_maximum_nights',
 'maximum_maximum_nights',
 'minimum_nights_avg_ntm',
 'maximum_nights_avg_ntm',
 'calendar_updated',
 'has_availability',
 'availability_30',
 'availability_60',
 'availability_90',
 'availability_365',
 'calendar_last_scraped',
 'number_of_reviews',
 'number_of_reviews_ltm',
 'number_of_reviews_l30d',
 'first_review',
 'last_review',
 'review_scores_rating',
 'review_scores_accuracy',
 'review_scores_cleanliness',
 'review_scores_checkin',
 'review_scores_communication',
 'review_scores_location',
 'review_scores_value',
 'license',
 'instant_bookable',
 'calculated_host_listings_count',
 'calculated_host_listings_count_entire_homes',
 'calculated_host_listings_count_private_rooms',
 'calculated_host_listings_count_shared_rooms',
 'reviews_per_month']

In [13]:
listings_2 = pd.read_csv('./primary/listings-2.csv')
listings_2.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,3686,Vita's Hideaway,4645,Vita,NaN,Historic Anacostia,38.863390,-76.988890,Private room,67,31,81,2022-07-06,0.54,1,211,2,NaN
1,871825,Prime location on Capitol Hill,4597024,Rich And Betsy,NaN,"Capitol Hill, Lincoln Park",38.884420,-77.004910,Entire home/apt,120,31,18,2021-06-28,0.17,1,0,0,NaN
2,116951,Upscale Private Close to Everything,481929,Chris,NaN,"Howard University, Le Droit Park, Cardozo/Shaw",38.914359,-77.018099,Private room,75,31,83,2022-10-26,0.58,4,336,3,NaN
3,150109,Great apartment in perfect location,723470,Steffanie,NaN,"Dupont Circle, Connecticut Avenue/K Street",38.915250,-77.040010,Entire home/apt,135,31,31,2022-03-01,0.22,1,38,0,NaN
4,153545,Guest Room 3 miles to the White House,738459,Natasha,NaN,"Brightwood Park, Crestwood, Petworth",38.942860,-77.044170,Private room,49,30,38,2022-06-21,0.27,5,310,1,Hosted License: 5007242201000811\nUnhosted Lic...

In [14]:
listings_2.columns.to_list()

['id',
 'name',
 'host_id',
 'host_name',
 'neighbourhood_group',
 'neighbourhood',
 'latitude',
 'longitude',
 'room_type',
 'price',
 'minimum_nights',
 'number_of_reviews',
 'last_review',
 'reviews_per_month',
 'calculated_host_listings_count',
 'availability_365',
 'number_of_reviews_ltm',
 'license']

In [7]:
neighborhoods = pd.read_csv('./primary/neighbourhoods.csv')
neighborhoods.head()

   neighbourhood_group                                    neighbourhood
0                  NaN             Brightwood Park, Crestwood, Petworth
1                  NaN                    Brookland, Brentwood, Langdon
2                  NaN                       Capitol Hill, Lincoln Park
3                  NaN  Capitol View, Marshall Heights, Benning Heights
4                  NaN   Cathedral Heights, McLean Gardens, Glover Park

In [9]:
reviews = pd.read_csv('./primary/reviews.csv')
reviews.head()

,listing_id,id,date,reviewer_id,reviewer_name,comments
0,3686,131293,2010-11-01,257234,Callie,Staying with Levita and her wonderful family w...
1,3686,150766,2010-12-08,255888,Patrick,"Vita is a very welcoming, helpful and friendly..."
2,3686,177749,2011-02-02,366688,Benjamin,"This was my first time using ""airbnb"" and it m..."
3,3686,197451,2011-03-12,213492,T.J.,"First, Vita saved my work week by providing me..."
4,3686,213212,2011-03-30,428455,Pete,Great host! Very welcoming and organised. I st...

"reviews" also contains a listing id, along with its own unique id.

In [10]:
reviews_2 = pd.read_csv('./primary/reviews-2.csv')
reviews_2.head()

   listing_id        date
0        3686  2010-11-01
1        3686  2010-12-08
2        3686  2011-02-02
3        3686  2011-03-12
4        3686  2011-03-30